version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123456
      POSTGRES_DB: blogdb
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    restart: always
